# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import rocksplicator_pb2 as rocksplicator__pb2


class RocksplicatorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetNum = channel.unary_stream(
        '/rocksplicator.Rocksplicator/GetNum',
        request_serializer=rocksplicator__pb2.Empty.SerializeToString,
        response_deserializer=rocksplicator__pb2.Response.FromString,
        )


class RocksplicatorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetNum(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RocksplicatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetNum': grpc.unary_stream_rpc_method_handler(
          servicer.GetNum,
          request_deserializer=rocksplicator__pb2.Empty.FromString,
          response_serializer=rocksplicator__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'rocksplicator.Rocksplicator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
