# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rocksplicator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rocksplicator.proto',
  package='rocksplicator',
  syntax='proto3',
  serialized_pb=_b('\n\x13rocksplicator.proto\x12\rrocksplicator\"\x16\n\x07Request\x12\x0b\n\x03uid\x18\x01 \x01(\r\"\x17\n\x08Response\x12\x0b\n\x03uid\x18\x01 \x03(\r\"\x07\n\x05\x45mpty2J\n\rRocksplicator\x12\x39\n\x06GetNum\x12\x14.rocksplicator.Empty\x1a\x17.rocksplicator.Response0\x01\x62\x06proto3')
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='rocksplicator.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='rocksplicator.Request.uid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=60,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='rocksplicator.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='rocksplicator.Response.uid', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=85,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='rocksplicator.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=94,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'rocksplicator_pb2'
  # @@protoc_insertion_point(class_scope:rocksplicator.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'rocksplicator_pb2'
  # @@protoc_insertion_point(class_scope:rocksplicator.Response)
  ))
_sym_db.RegisterMessage(Response)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'rocksplicator_pb2'
  # @@protoc_insertion_point(class_scope:rocksplicator.Empty)
  ))
_sym_db.RegisterMessage(Empty)



_ROCKSPLICATOR = _descriptor.ServiceDescriptor(
  name='Rocksplicator',
  full_name='rocksplicator.Rocksplicator',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=96,
  serialized_end=170,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetNum',
    full_name='rocksplicator.Rocksplicator.GetNum',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_RESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROCKSPLICATOR)

DESCRIPTOR.services_by_name['Rocksplicator'] = _ROCKSPLICATOR

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class RocksplicatorStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.GetNum = channel.unary_stream(
          '/rocksplicator.Rocksplicator/GetNum',
          request_serializer=Empty.SerializeToString,
          response_deserializer=Response.FromString,
          )


  class RocksplicatorServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def GetNum(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_RocksplicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetNum': grpc.unary_stream_rpc_method_handler(
            servicer.GetNum,
            request_deserializer=Empty.FromString,
            response_serializer=Response.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'rocksplicator.Rocksplicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaRocksplicatorServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def GetNum(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaRocksplicatorStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def GetNum(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()


  def beta_create_Rocksplicator_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('rocksplicator.Rocksplicator', 'GetNum'): Empty.FromString,
    }
    response_serializers = {
      ('rocksplicator.Rocksplicator', 'GetNum'): Response.SerializeToString,
    }
    method_implementations = {
      ('rocksplicator.Rocksplicator', 'GetNum'): face_utilities.unary_stream_inline(servicer.GetNum),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Rocksplicator_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('rocksplicator.Rocksplicator', 'GetNum'): Empty.SerializeToString,
    }
    response_deserializers = {
      ('rocksplicator.Rocksplicator', 'GetNum'): Response.FromString,
    }
    cardinalities = {
      'GetNum': cardinality.Cardinality.UNARY_STREAM,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'rocksplicator.Rocksplicator', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
